ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls')),
    path('order/', include('orders.urls')),
]
if settings.DEBUG:  # new
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from orders import views

urlpatterns = [

    path('orders/', views.OrderListView.as_view(), name='order_list'),

]

product/urls.py
from product import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


app_name = 'product'
# from django.urls import reverse_lazy
urlpatterns = [

    path('', views.Base, name='base'),
    path('product/', views.ProductListView.as_view(), name='index'),
    path('product/detail/<int:pk>',
         views.ProductDetailView.as_view(), name='product_detail'),
    path('product/delete/<int:pk>',
         views.ProductDeleteView.as_view(), name='delete'),
    path('product/update/<int:pk>',
         views.ProductUpdateView.as_view(), name='update'),
    path('product/create/', views.ProductCreateView.as_view(), name='create'),
    path('price/list/', views.ProductPriceList.as_view(), name='price_list'),
    path('category/list/', views.CategoryList.as_view(), name='category_list'),

]
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from product.models import Product

# Create your models here.
METHOD = (('Cash', 'Cash'),
          ('Fonepay', 'Fonepay'),
          ('Esewa', 'Esewa'),
          ('Bank', 'Bank'))


class OrderItem(models.Model):
    quantity = models.CharField(max_length=200)
    subtotal = models.FloatField()
    created_at = models.DateField()
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return self.subtotal


class FinalOrder(models.Model):
    order_item_id = models.ForeignKey(OrderItem, on_delete=models.CASCADE)
    # payment_id = models.ForeignKey(Payment, on_delete=models.CASCADE)


class Payment(models.Model):
    name = models.CharField(max_length=300)
    final_order_id = models.ForeignKey(FinalOrder, on_delete=models.CASCADE)
    payment_method = models.CharField(choices=METHOD, max_length=100)
    amount = models.FloatField()

    def __str__(self):
        return self.name


class Shipment(models.Model):
    payment = models.ForeignKey(Payment, on_delete=models.CASCADE)
    final_oder_id = models.ForeignKey(FinalOrder, on_delete=models.CASCADE)
    shipment_date = models.DateField()

    # def __str__(self):
    #     return  f'{orders.payment}-{orders.shipment_date}'


class Address(models.Model):
    city = models.CharField(max_length=100)
    ward_no = models.BigIntegerField()
    tole_name = models.CharField(max_length=100)
    landmark = models.CharField(max_length=100)

    def __str__(self):
        return self.city

product/models.py
from django.db import models

# Create your models here.


class ProductManager(models.Manager):
    def category(self, category_name):
        return self.get_queryset().filter(category_name=category_name)

    def get_queryset(self):
        return super().get_queryset().filter(price__gt=200)


class Category(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=300)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.FloatField()
    summer_coll = models.CharField(max_length=200)
    autmon_coll = models.CharField(max_length=200)
    # inventary=models.ForeignKey
    hot_sell = models.CharField(max_length=200)
    discount = models.CharField(max_length=200)
    description = models.TextField(null=True)
    image = models.ImageField(upload_to='static', null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    custom_objects = ProductManager()

    def __str__(self):
        return self.name


class Discount(models.Model):
    name = models.CharField(max_length=300)
    discount = models.CharField(max_length=200)
    status = models.CharField(max_length=200)

    def __Str__(self):
        return self.name

product/forms.py
from django import forms
from product.models import *


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
    #   <!--   widgets = {
    #         'name': forms.TextInput(attrs={'class': 'forms.control'}),

    #         'quantity': forms.TextInput(attrs={'class': 'forms.control'}),
    #         'price': forms.TextInput(attrs={'class': 'forms.control'}),
    #         'summer_coll': forms.TextInput(attrs={'class': 'forms.control'}),
    #         'autmon_coll': forms.TextInput(attrs={'class': 'forms.control'}),
    #         'hot_sell': forms.TextInput(attrs={'class': 'forms.control'}),
    #         'discount': forms.TextInput(attrs={'class': 'forms.control'}),
    #         'created_at': forms.TextInput(attrs={'class': 'forms.control'}),

    #     } -->

orders/views.py
from django.shortcuts import render
from orders.models import *
from django.views.generic import ListView
# , DetailView, CreateView
# Create your views here.


class OrderListView(ListView):
    model = OrderItem

product/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render
# from django.views.generic import ListView
from product.models import Product
from django.views.generic import ListView, DetailView, CreateView
from product.forms import ProductForm
# CreateView, UpdateView, DeleteView, DetailView
from django.urls import reverse_lazy
# Create your views here.


def Base(request):
    return render(request, 'product/base.html')


class ProductListView(ListView):
    model = Product
    # form_class = ProductForm
    template_name = 'product/product_list.html'


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/form.html'
    success_url = reverse_lazy('product:index')


class ProductDetailView(DetailView):
    model = Product
    # form_class = ProductForm
    template_name = 'product/detail.html'
    success_url = reverse_lazy('product:index')


class ProductDeleteView(DetailView):
    model = Product
    # form_class = ProductForm
    template_name = 'product/delete.html'
    success_url = reverse_lazy('product:index')


class ProductUpdateView(DetailView):
    model = Product
    form_class = ProductForm
    template_name = 'product/form.html'
    success_url = reverse_lazy('product:index')


class ProductPriceList(ListView):
    model = Product
    template_name = 'product/product_price.html'
    queryset = Product.custom_objects.all().filter(price__gte=800)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['list'] = self.queryset
        return context

    def get_queryset(self):
        return super().get_queryset()


class CategoryList(ListView):
    model = Product
    template_name = 'product/category_list.html'
    context_object_name = 'list'
    queryset = Product.custom_objects.filter(price__gte=500)

    # def product_list(request):
    #     filter = Product(
    #         request.GET, queryset=Product.custom_objects.all().filter)
    #     return render(request, 'product/product_price.html', {'filter': filter})

product/templates/product/delete.html
<div class="bg-white py-24 sm:py-32">
    <div class="mx-auto max-w-7xl px-6 lg:px-8">
      <div class="mx-auto max-w-2xl lg:mx-0">
        <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">From the blog</h2>
        <p class="mt-2 text-lg leading-8 text-gray-600">Learn how to grow your business with our expert advice.</p>
      </div>
      <div class="mx-auto mt-10 grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 border-t border-gray-200 pt-10 sm:mt-16 sm:pt-16 lg:mx-0 lg:max-w-none lg:grid-cols-3">
        <article class="flex max-w-xl flex-col items-start justify-between">
          <div class="flex items-center gap-x-4 text-xs">
            <time datetime="2020-03-16" class="text-gray-500">Mar 16, 2020</time>
            <a href="#" class="relative z-10 rounded-full bg-gray-50 px-3 py-1.5 font-medium text-gray-600 hover:bg-gray-100">Marketing</a>
          </div>
          <div class="group relative">
            <h3 class="mt-3 text-lg font-semibold leading-6 text-gray-900 group-hover:text-gray-600">
              <a href="#">
                <span class="absolute inset-0"></span>
                Boost your conversion rate
              </a>
            </h3>
            <p class="mt-5 line-clamp-3 text-sm leading-6 text-gray-600">Illo sint voluptas. Error voluptates culpa eligendi. Hic vel totam vitae illo. Non aliquid explicabo necessitatibus unde. Sed exercitationem placeat consectetur nulla deserunt vel. Iusto corrupti dicta.</p>
          </div>
          <div class="relative mt-8 flex items-center gap-x-4">
            <img src="https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" class="h-10 w-10 rounded-full bg-gray-50">
            <div class="text-sm leading-6">
              <p class="font-semibold text-gray-900">
                <a href="#">
                  <span class="absolute inset-0"></span>
                  Michael Foster
                </a>
              </p>
              <p class="text-gray-600">Co-Founder / CTO</p>
            </div>
          </div>
        </article>
  
        <!-- More posts... -->
      </div>
    </div>
  </div>

product/templates/product/detail.html
{% extends '../product/base.html' %}
{% block content %}


    <body>
        <form method='POST'>
            {%  csrf_token %} 
            {{ form.as_p }}
            <a href="{% url 'product:index'%}">Update</a>
            <a href="{% url 'product:index' %}">Delete</a>
 
       <section class="text-gray-600 body-font overflow-hidden">
              <div class="container col-md-4 px-20 py-24 mx-auto">
               
                <div class="lg:w-4/5 mx-auto flex flex-wrap">
                  <img alt="{{ product.name }}"  class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="{{ product.image.url}}">
                  
                  <div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
                    <h2 class="text-sm title-font text-gray-500 tracking-widest">{{ product.name }}</h2>
                    <h1 class="text-gray-900 text-3xl title-font font-medium mb-1">{{ product.category }}</h1>
                    <div class="flex mb-4">
                      <span class="flex items-center">
                        <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 text-indigo-500" viewBox="0 0 24 24">
                          <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"></path>
                        </svg>
                        <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 text-indigo-500" viewBox="0 0 24 24">
                          <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"></path>
                        </svg>
                        <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 text-indigo-500" viewBox="0 0 24 24">
                          <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"></path>
                        </svg>
                        <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 text-indigo-500" viewBox="0 0 24 24">
                          <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"></path>
                        </svg>
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 text-indigo-500" viewBox="0 0 24 24">
                          <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"></path>
                        </svg>
                        <span class="text-gray-600 ml-3">{{ product.price }}</span>
                      </span>
                      <span class="flex ml-3 pl-3 py-2 border-l-2 border-gray-200 space-x-2s">
                        <a class="text-gray-500">
                          <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                            <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
                          </svg>
                        </a>
                        <a class="text-gray-500">
                          <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                            <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
                          </svg>
                        </a>
                        <a class="text-gray-500">
                          <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                            <path d="M21 11.5a8.38 8.38 0 01-.9 3.8 8.5 8.5 0 01-7.6 4.7 8.38 8.38 0 01-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 01-.9-3.8 8.5 8.5 0 014.7-7.6 8.38 8.38 0 013.8-.9h.5a8.48 8.48 0 018 8v.5z"></path>
                          </svg>
                        </a>
                      </span>
                    </div>
                    <p class="leading-relaxed">{{ product.description }}</p>
                    <div class="flex mt-6 items-center pb-5 border-b-2 border-gray-100 mb-5">
                        <!-- <div class="flex">
                        <span class="mr-3">Color</span>
                        <button class="border-2 border-gray-300 rounded-full w-6 h-6 focus:outline-none"></button>
                        <button class="border-2 border-gray-300 ml-1 bg-gray-700 rounded-full w-6 h-6 focus:outline-none"></button>
                        <button class="border-2 border-gray-300 ml-1 bg-indigo-500 rounded-full w-6 h-6 focus:outline-none"></button>
                      </div>
                     <div class="flex ml-6 items-center">
                        <span class="mr-3">Size</span>
                        <div class="relative">
                          <select class="rounded border appearance-none border-gray-300 py-2 focus:outline-none focus:ring-2 focus:ring-indigo-200 focus:border-indigo-500 text-base pl-3 pr-10">
                            <option>SM</option>
                            <option>M</option>
                            <option>L</option>
                            <option>XL</option>
                          </select>
                          <span class="absolute right-0 top-0 h-full w-10 text-center text-gray-600 pointer-events-none flex items-center justify-center">
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4" viewBox="0 0 24 24">
                              <path d="M6 9l6 6 6-6"></path>
                            </svg>
                          </span>
                        </div>
                      </div>
                    </div> -->
                    <div class="flex">
                      <span class="title-font font-medium text-2xl text-gray-900">{{ product.price }}</span>
                      <!-- <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Button</button>-->
                      <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
                        <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                          <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
                        </svg>
                      </button>
                    </div>
                  </div>
                </div>
               
              </div>
          </section>
          
    
    
        </body>
    {% endblock %}

product/templates/product/form.html
{% extends '../product/base.html' %} {% block content %}
<div class="section">
  <div class="container">
    <div class="container-fluid">
      <div class="card">
        <div class="card-header">
          <h4>Add Product</h4>
        </div>
        <div class="card-body">
          <div class="form group row">
           <!--  <div class="col-md-8">
              <form method="POST">
                {% csrf_token %} {{ form.as_p }} {{ cripsy_form }}
                <button type="submit">save me</button>
              </form>
            </div> -- >
            <div class="bg-gray-100  p-6 flex items-center justify-center h-screen">
              <h2 class="text-2xl font-semibold mb-4">Create a new product</h2>
              
              <form method="post" action="{% url 'product:create' %}" enctype="multipart/form-data" class="max-w-md bg-white p-6 rounded-md shadow-md">
                  {% csrf_token %}
                  
                  <!-- Product Name -->
                  <div class="mb-1">
                      <label for="id_name" class="block text-gray-700 text-sm font-bold mb-2">Product Name</label>
                      <input type="text" name="name" id="id_name" class="w-100%  border rounded-md p-2" required>
                  </div>
          
                  <div class="mb-4">
                    <label for="id_image" class="block text-gray-700 text-sm font-bold mb-2">Category</label>
                    <input type="text" name="category" id="category" class="w-75% border rounded-md p-2">
                </div>
                   <!-- quantity-->
                   <div class="mb-1">
                    <label for="id_name" class="block text-gray-700 text-sm font-bold mb-2">Quantity</label>
                    <input type="text" name="quantity" id="quantity" class="w-100%  border rounded-md p-2" required>
                </div>
                   <!-- Product Name -->
                   <div class="mb-1">
                    <label for="price" class="block text-gray-700 text-sm font-bold mb-2">Product Price</label>
                    <input type="text" name="price" id="price" class="w-100%  border rounded-md p-2" required>
                </div>

                   <!-- Product Name -->
                   <div class="mb-1">
                    <label for="summer_coll" class="block text-gray-700 text-sm font-bold mb-2">Summer Collection</label>
                    <input type="text" name="summer_coll" id="summer_coll" class="w-100%  border rounded-md p-2" required>
                </div>
          
                   <!-- Product Name -->
                   <div class="mb-1">
                    <label for="autmon_coll" class="block text-gray-700 text-sm font-bold mb-2">Autmon Collection</label>
                    <input type="text" name="autmon_coll" id="autmon_coll" class="w-100%  border rounded-md p-2" required>
                </div>
                
                   <!-- hot sell -->
                   <div class="mb-1">
                    <label for="hot_sell" class="block text-gray-700 text-sm font-bold mb-2">hot sell</label>
                    <input type="text" name="hot_sell" id="hot_sell" class="w-100%  border rounded-md p-2" required>
                </div>

                
                   <!-- Product Name -->
                   <div class="mb-1">
                    <label for="summer_coll" class="block text-gray-700 text-sm font-bold mb-2">discount</label>
                    <input type="text" name="discount" id="summer_coll" class="w-100%  border rounded-md p-2" required>
                </div>
                
                   <!-- Product Name -->
                   <div class="mb-1">
                    <label for="summer_coll" class="block text-gray-700 text-sm font-bold mb-2">description</label>
                    <input type="text" name="description" id="summer_coll" class="w-100%  border rounded-md p-2" required>
                </div>
                  <!-- Image Upload -->
                  <div class="mb-4">
                      <label for="id_image" class="block text-gray-700 text-sm font-bold mb-2">Product Image</label>
                      <input type="file" name="image" id="id_image" class="w-75% border rounded-md p-2">
                  </div>
              
          
                  <button type="submit" class="bg-blue-500 text-white py-2 px-4 rounded-md hover:bg-blue-700">Save Product</button>
              </form>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

product/templates/product/product_list.html
{% extends '../product/base.html' %}
{% load static %}
{% block content %}

<div class="container-wrapper">
  <!-- Main content 
  <section class="content"> -->
    <form>   
      <label for="default-search" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-gray-300">Search</label>
      <div class="relative">
          <div class="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
              <svg class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
          </div>
          <input type="search" id="default-search" class="block p-4 pl-10 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search Mockups, Logos..." required>
          <button type="submit" class="text-white absolute right-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Search</button>
      </div>
  </form>
      <div class="row">
          <div class="card">
                <div class='card-header'>product List
                  <a href="{% url 'product:create'%}" class='p-6'> Add product</a>
                </div>
                  <div class="card-body">
                    <div class="mt-6 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
                      {% for product in object_list %}
                          <div class="group relative">
                              <div class="aspect-h-1 aspect-w-1 w-full overflow-hidden rounded-md bg-gray-200 lg:aspect-none group-hover:opacity-75 lg:h-80">
                                <!--  <img src="{% static 'product/dj-logo.jpg' %}" alt="Product Image" class="h-full w-full object-cover object-center lg:h-full lg:w-full" /> --> 
                                <img src="{{ product.image.url }}" alt="{{ product.name }}" class="h-full w-full object-cover object-center lg:h-full lg:w-full" />
                                </div>
                              <div class="mt-4 flex justify-between">
                                  <div>
                                      <h3 class="text-sm text-gray-700">
                                          <a href="{% url 'product:product_detail' product.id %}">
                                              <span aria-hidden="true" class="absolute inset-0"></span>
                                              {{ product.name }}
                                          </a>
                                      </h3>
                                      <p class="mt-1 text-sm text-gray-500">{{ product.category }}</p>
                                  </div>
                                  <p class="text-sm font-medium text-gray-900">{{ product.price }}</p>
                              </div>
                          </div>
                      {% endfor %}
                    
                    </div>  
                  </div>
      
          </div>
        </div>
      </div>
  </div>
  <!-- /.container-fluid 
  </section>-->
</div>
<!-- /.content -->
   
{% endblock %}

product/templates/product/product_price.html
{% extends '../product/base.html' %}
{% load static %}
{% block content %}

<div class="container-wrapper">
  <!-- Main content 
  <section class="content"> -->
    <form>   
      <label for="default-search" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-gray-300">Search</label>
      <div class="relative">
          <div class="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
              <svg class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
          </div>
          <input type="search" id="default-search" class="block p-4 pl-10 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search Mockups, Logos..." required>
          <button type="submit" class="text-white absolute right-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Search</button>
      </div>
  </form>
      <div class="row">
          <div class="card">
                <div class='card-header'>product List
                  <a href="{% url 'product:create'%}" class='p-6'> Add product</a>
                </div>
                  <div class="card-body">
                    <div class="mt-6 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
                      {% for product in object_list %}
                          <div class="group relative">
                              <div class="aspect-h-1 aspect-w-1 w-full overflow-hidden rounded-md bg-gray-200 lg:aspect-none group-hover:opacity-75 lg:h-80">
                                  <img src="{% static 'product/dj-logo.jpg' %}" alt="Product Image" class="h-full w-full object-cover object-center lg:h-full lg:w-full" />
                              </div>
                              <div class="mt-4 flex justify-between">
                                  <div>
                                      <h3 class="text-sm text-gray-700">
                                          <a href="{% url 'product:product_detail' product.id %}">
                                              <span aria-hidden="true" class="absolute inset-0"></span>
                                              {{ product.name }}
                                          </a>
                                      </h3>
                                      <p class="mt-1 text-sm text-gray-500">{{ product.category }}</p>
                                  </div>
                                  <p class="text-sm font-medium text-gray-900">{{ product.price }}</p>
                              </div>
                          </div>
                      {% endfor %}
                    
                    </div>  
                  </div>
      
          </div>
        </div>
      </div>
  </div>
  <!-- /.container-fluid 
  </section>-->
</div>
<!-- /.content -->
   
{% endblock %}